#Think of at least five places in the world you’d like to visit Store the locations in a list. Make sure the list is not in alphabetical order.

location =['INDIA','AMERICA','COLOMBIA','SRILANKA','ISTANBUL']
print("correct order:")
print(location)
print("\nAlphabetical:")
print(sorted(location))
print("\nReverse alphabetical:")
print(sorted(location, reverse=True))
print("\nreal order:")
print(location)
print("\nReversed:")
location.reverse()
print(location)
print("\nreal order:")
location.reverse()
print(location)
print("\nAlphabetical")
location.sort()
print(location)
print("\nReverse alphabetical")
location.sort(reverse=True)
print(location)