name=input("ENTER YOUR NAME:")
age=input("ENTER YOUR AGE:")
university=input("ENTER YOUR UNI NAME:")
hobbies=input("ENTER YOUR HOBBIES:")
favouritemovie=input("ENTER YOUR FAV MOVIE:")
nationality=input("ENTER YOUR NATIONALITY:")
favouritefootballer=input("ENTER FAVOURITE FOOTBALLER NAME:")
print("*********THANK YOU FOR ENTERING THE DEATILS*********")
print(name)
print(age)
print(university)
print(hobbies)
print(favouritemovie)
print(nationality)
print(favouritefootballer)